// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `HelloSlice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <HelloSlice.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_HelloSlice_HelloServiceItf_ids[2] =
{
    "::HelloSlice::HelloServiceItf",
    "::Ice::Object"
};
const ::std::string iceC_HelloSlice_HelloServiceItf_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sayHello"
};
const ::std::string iceC_HelloSlice_HelloServiceItf_sayHello_name = "sayHello";

}

bool
HelloSlice::HelloServiceItf::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_HelloSlice_HelloServiceItf_ids, iceC_HelloSlice_HelloServiceItf_ids + 2, s);
}

::std::vector<::std::string>
HelloSlice::HelloServiceItf::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_HelloSlice_HelloServiceItf_ids[0], &iceC_HelloSlice_HelloServiceItf_ids[2]);
}

::std::string
HelloSlice::HelloServiceItf::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
HelloSlice::HelloServiceItf::ice_staticId()
{
    static const ::std::string typeId = "::HelloSlice::HelloServiceItf";
    return typeId;
}

bool
HelloSlice::HelloServiceItf::_iceD_sayHello(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    this->sayHello(::std::move(iceP_s), current);
    inS.writeEmptyParams();
    return true;
}

bool
HelloSlice::HelloServiceItf::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_HelloSlice_HelloServiceItf_ops, iceC_HelloSlice_HelloServiceItf_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_HelloSlice_HelloServiceItf_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sayHello(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
HelloSlice::HelloServiceItfPrx::_iceI_sayHello(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_HelloSlice_HelloServiceItf_sayHello_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
HelloSlice::HelloServiceItfPrx::_newInstance() const
{
    return ::IceInternal::createProxy<HelloServiceItfPrx>();
}

const ::std::string&
HelloSlice::HelloServiceItfPrx::ice_staticId()
{
    return HelloSlice::HelloServiceItf::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_HelloSlice_HelloServiceItf_sayHello_name = "sayHello";

}
::IceProxy::Ice::Object* ::IceProxy::HelloSlice::upCast(::IceProxy::HelloSlice::HelloServiceItf* p) { return p; }

void
::IceProxy::HelloSlice::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::HelloSlice::HelloServiceItf>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::HelloSlice::HelloServiceItf;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::HelloSlice::HelloServiceItf::_iceI_begin_sayHello(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_HelloSlice_HelloServiceItf_sayHello_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_HelloSlice_HelloServiceItf_sayHello_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_HelloSlice_HelloServiceItf_sayHello_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::HelloSlice::HelloServiceItf::end_sayHello(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_HelloSlice_HelloServiceItf_sayHello_name);
}

::IceProxy::Ice::Object*
IceProxy::HelloSlice::HelloServiceItf::_newInstance() const
{
    return new HelloServiceItf;
}

const ::std::string&
IceProxy::HelloSlice::HelloServiceItf::ice_staticId()
{
    return ::HelloSlice::HelloServiceItf::ice_staticId();
}

HelloSlice::HelloServiceItf::~HelloServiceItf()
{
}

::Ice::Object* HelloSlice::upCast(::HelloSlice::HelloServiceItf* p) { return p; }


namespace
{
const ::std::string iceC_HelloSlice_HelloServiceItf_ids[2] =
{
    "::HelloSlice::HelloServiceItf",
    "::Ice::Object"
};

}

bool
HelloSlice::HelloServiceItf::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_HelloSlice_HelloServiceItf_ids, iceC_HelloSlice_HelloServiceItf_ids + 2, s);
}

::std::vector< ::std::string>
HelloSlice::HelloServiceItf::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_HelloSlice_HelloServiceItf_ids[0], &iceC_HelloSlice_HelloServiceItf_ids[2]);
}

const ::std::string&
HelloSlice::HelloServiceItf::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
HelloSlice::HelloServiceItf::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::HelloSlice::HelloServiceItf";
    return typeId;
#else
    return iceC_HelloSlice_HelloServiceItf_ids[0];
#endif
}

bool
HelloSlice::HelloServiceItf::_iceD_sayHello(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    this->sayHello(iceP_s, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_HelloSlice_HelloServiceItf_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sayHello"
};

}

bool
HelloSlice::HelloServiceItf::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_HelloSlice_HelloServiceItf_all, iceC_HelloSlice_HelloServiceItf_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_HelloSlice_HelloServiceItf_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sayHello(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
HelloSlice::HelloServiceItf::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::HelloSlice::HelloServiceItf, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
HelloSlice::HelloServiceItf::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::HelloSlice::HelloServiceItf, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
HelloSlice::_icePatchObjectPtr(HelloServiceItfPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::HelloSlice::HelloServiceItfPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::HelloSlice::HelloServiceItf::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
