// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `HelloSlice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __HelloSlice_h__
#define __HelloSlice_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace HelloSlice
{

class HelloServiceItf;
class HelloServiceItfPrx;

}

namespace HelloSlice
{

class HelloServiceItf : public virtual ::Ice::Object
{
public:

    using ProxyType = HelloServiceItfPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void sayHello(::std::string, const ::Ice::Current&) = 0;
    bool _iceD_sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace HelloSlice
{

class HelloServiceItfPrx : public virtual ::Ice::Proxy<HelloServiceItfPrx, ::Ice::ObjectPrx>
{
public:

    void sayHello(const ::std::string& iceP_s, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &HelloSlice::HelloServiceItfPrx::_iceI_sayHello, iceP_s, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto sayHelloAsync(const ::std::string& iceP_s, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &HelloSlice::HelloServiceItfPrx::_iceI_sayHello, iceP_s, context);
    }

    ::std::function<void()>
    sayHelloAsync(const ::std::string& iceP_s,
                  ::std::function<void()> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &HelloSlice::HelloServiceItfPrx::_iceI_sayHello, iceP_s, context);
    }

    void _iceI_sayHello(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::std::string&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    HelloServiceItfPrx() = default;
    friend ::std::shared_ptr<HelloServiceItfPrx> IceInternal::createProxy<HelloServiceItfPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

}

namespace HelloSlice
{

using HelloServiceItfPtr = ::std::shared_ptr<HelloServiceItf>;
using HelloServiceItfPrxPtr = ::std::shared_ptr<HelloServiceItfPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace HelloSlice
{

class HelloServiceItf;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::HelloSlice::HelloServiceItf>&);
::IceProxy::Ice::Object* upCast(::IceProxy::HelloSlice::HelloServiceItf*);

}

}

namespace HelloSlice
{

class HelloServiceItf;
::Ice::Object* upCast(::HelloSlice::HelloServiceItf*);
typedef ::IceInternal::Handle< ::HelloSlice::HelloServiceItf> HelloServiceItfPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::HelloSlice::HelloServiceItf> HelloServiceItfPrx;
typedef HelloServiceItfPrx HelloServiceItfPrxPtr;
void _icePatchObjectPtr(HelloServiceItfPtr&, const ::Ice::ObjectPtr&);

}

namespace HelloSlice
{

class Callback_HelloServiceItf_sayHello_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_HelloServiceItf_sayHello_Base> Callback_HelloServiceItf_sayHelloPtr;

}

namespace IceProxy
{

namespace HelloSlice
{

class HelloServiceItf : public virtual ::Ice::Proxy<HelloServiceItf, ::IceProxy::Ice::Object>
{
public:

    void sayHello(const ::std::string& iceP_s, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_sayHello(_iceI_begin_sayHello(iceP_s, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& iceP_s, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_sayHello(iceP_s, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& iceP_s, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(iceP_s, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& iceP_s, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(iceP_s, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& iceP_s, const ::HelloSlice::Callback_HelloServiceItf_sayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(iceP_s, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& iceP_s, const ::Ice::Context& context, const ::HelloSlice::Callback_HelloServiceItf_sayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_sayHello(iceP_s, context, del, cookie);
    }

    void end_sayHello(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_sayHello(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace HelloSlice
{

class HelloServiceItf : public virtual ::Ice::Object
{
public:

    typedef HelloServiceItfPrx ProxyType;
    typedef HelloServiceItfPtr PointerType;

    virtual ~HelloServiceItf();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void sayHello(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const HelloServiceItf& lhs, const HelloServiceItf& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const HelloServiceItf& lhs, const HelloServiceItf& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

}

namespace HelloSlice
{

template<class T>
class CallbackNC_HelloServiceItf_sayHello : public Callback_HelloServiceItf_sayHello_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_HelloServiceItf_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_HelloServiceItf_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_HelloServiceItf_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_HelloServiceItf_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_HelloServiceItf_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_HelloServiceItf_sayHello : public Callback_HelloServiceItf_sayHello_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_HelloServiceItf_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_HelloServiceItf_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_HelloServiceItf_sayHello<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_HelloServiceItf_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_HelloServiceItf_sayHelloPtr
newCallback_HelloServiceItf_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_HelloServiceItf_sayHello<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
